### ISSUE TITLE
ELMo 4-layer variant

### ISSUE THREAD

**Issue by Superhzf** [nelson-liu/contextual-repr-analysis#10]
Hi @nelson-liu 

I'm trying to reproduce the results of this paper https://aclanthology.org/2020.acl-main.422.pdf, where the authors take the advantage of the settings in this repo.

I am wondering whether you can kindly share the trained model of the ELMo 4-layer variant. I can't find it on the Allennlp ELMo page https://allennlp.org/elmo.

**Comment by nelson-liu** [comment]
Unfortunately, I don't have access to the model anymore---it's an AI2-internal model that I don't think they plan to release.
