### ISSUE TITLE
How to get hdf5 file?

### ISSUE THREAD

**Issue by longxudou** [nelson-liu/contextual-repr-analysis#5]
How to get `contextualizers/elmo_original/ewt_pos.hdf5` in ewt_pos_tagging.json to run example? What should I run in Step 1. Precomputing the Word Representations.
Thx!

**Comment by nelson-liu** [comment]
You can use the `allennlp elmo` command, or write your own script to extract the vectors and format them as specified.

**Comment by longxudou** [comment]
Noted.
Thank you for such wonderful package.
