### ISSUE TITLE
Preparing data for (GC)Parent and CCG Tasks

### ISSUE THREAD

**Issue by oshaikh13** [nelson-liu/contextual-repr-analysis#6]
Hey!

I'm trying to run these tasks on some embeddings but I've run into 2 problems for dataset prep:

1) I'm not sure how I'd go about linearizing the PTB trees for the (GC)Parent tasks. The code depends on "wsj.{train,test,dev}.trees." Do I just remove the newlines in the .prd files from the original dataset to get these files?
2) For the CCG Tasks, do I just concatenate the .auto files (from the original dataset) using the same PTB splits for train/dev/test to get the "ccg/{train,test,dev}.txt" files?

Thanks a ton for this btw!
Omar

**Comment by nelson-liu** [comment]
> I'm not sure how I'd go about linearizing the PTB trees for the (GC)Parent tasks. The code depends on "wsj.{train,test,dev}.trees." Do I just remove the newlines in the .prd files from the original dataset to get these files?

I think that generating the processed data files is unfortunately somewhat of a lost art. https://github.com/jhcross/span-parser/issues/3 If you email me, I can give you more info.

> For the CCG Tasks, do I just concatenate the .auto files (from the original dataset) using the same PTB splits for train/dev/test to get the "ccg/{train,test,dev}.txt" files?

Yup! In particular, the files were used with https://github.com/allenai/allennlp-models/blob/master/allennlp_models/tagging/dataset_readers/ccgbank.py#L22-L35

Closing this for now, feel free to follow up if you have any further questions.
